@extends('layouts.admin')

@section('title', 'Share Bonus Statement Details')
@section('subtitle', 'View detailed share bonus statement information')

@section('content')
<div class="space-y-6">
    <!-- Statement Header -->
    <div class="bg-white rounded-lg shadow p-6">
        <div class="flex justify-between items-center mb-4">
            <div>
                <h3 class="text-lg font-semibold text-gray-900">Share Bonus Statement #{{ $statement->statement_number }}</h3>
                <p class="text-sm text-gray-500">Generated on {{ $statement->generated_date->format('M d, Y') }}</p>
            </div>
            <div class="flex space-x-2">
                <a href="{{ route('admin.share-bonus.print', $statement->id) }}" 
                   target="_blank"
                   class="bg-blue-600 hover:bg-blue-700 text-white px-3 py-2 rounded-lg text-sm">
                    <i class="fas fa-print mr-1"></i> Print
                </a>
                <a href="{{ route('admin.share-bonus.export-pdf', $statement->id) }}" 
                   class="bg-red-600 hover:bg-red-700 text-white px-3 py-2 rounded-lg text-sm">
                    <i class="fas fa-file-pdf mr-1"></i> Export PDF
                </a>
                <a href="{{ route('admin.share-bonus.export-excel', $statement->id) }}" 
                   class="bg-green-600 hover:bg-green-700 text-white px-3 py-2 rounded-lg text-sm">
                    <i class="fas fa-file-excel mr-1"></i> Export Excel
                </a>
                <a href="{{ route('admin.share-bonus.index') }}" 
                   class="bg-gray-600 hover:bg-gray-700 text-white px-3 py-2 rounded-lg text-sm">
                    <i class="fas fa-arrow-left mr-1"></i> Back
                </a>
            </div>
        </div>
        
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div class="bg-gray-50 p-3 rounded-lg">
                <p class="text-sm text-gray-500">Period</p>
                <p class="font-medium">{{ $statement->period_description }}</p>
            </div>
            
            <div class="bg-gray-50 p-3 rounded-lg">
                <p class="text-sm text-gray-500">Branch</p>
                <p class="font-medium">{{ $statement->branch ? $statement->branch->name : 'All Branches' }}</p>
            </div>
            
            <div class="bg-gray-50 p-3 rounded-lg">
                <p class="text-sm text-gray-500">Status</p>
                <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium 
                    @if($statement->status === 'generated') bg-yellow-100 text-yellow-800
                    @elseif($statement->status === 'partially_applied') bg-blue-100 text-blue-800
                    @elseif($statement->status === 'fully_applied') bg-green-100 text-green-800
                    @else bg-gray-100 text-gray-800 @endif">
                    {{ ucfirst(str_replace('_', ' ', $statement->status)) }}
                </span>
            </div>
            
            <div class="bg-gray-50 p-3 rounded-lg">
                <p class="text-sm text-gray-500">Generated By</p>
                <p class="font-medium">{{ $statement->generatedBy->name ?? 'System' }}</p>
            </div>
        </div>
    </div>
    
    <!-- Financial Summary -->
    <div class="bg-white rounded-lg shadow p-6">
        <h3 class="text-lg font-semibold text-gray-900 mb-4">Financial Summary</h3>
        
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div class="bg-blue-50 p-4 rounded-lg">
                <div class="flex items-center">
                    <div class="flex-shrink-0">
                        <i class="fas fa-coins text-blue-600 text-xl"></i>
                    </div>
                    <div class="ml-3">
                        <p class="text-sm font-medium text-blue-900">Net Income</p>
                        <p class="text-lg font-semibold text-blue-900">{{ $statement->formatted_net_income }}</p>
                    </div>
                </div>
            </div>
            
            <div class="bg-green-50 p-4 rounded-lg">
                <div class="flex items-center">
                    <div class="flex-shrink-0">
                        <i class="fas fa-percentage text-green-600 text-xl"></i>
                    </div>
                    <div class="ml-3">
                        <p class="text-sm font-medium text-green-900">Share Bonus Pool</p>
                        <p class="text-lg font-semibold text-green-900">{{ $statement->formatted_share_bonus_pool }}</p>
                    </div>
                </div>
            </div>
            
            <div class="bg-purple-50 p-4 rounded-lg">
                <div class="flex items-center">
                    <div class="flex-shrink-0">
                        <i class="fas fa-piggy-bank text-purple-600 text-xl"></i>
                    </div>
                    <div class="ml-3">
                        <p class="text-sm font-medium text-purple-900">Total Savings</p>
                        <p class="text-lg font-semibold text-purple-900">{{ $statement->formatted_total_savings_balance }}</p>
                    </div>
                </div>
            </div>
            
            <div class="bg-orange-50 p-4 rounded-lg">
                <div class="flex items-center">
                    <div class="flex-shrink-0">
                        <i class="fas fa-users text-orange-600 text-xl"></i>
                    </div>
                    <div class="ml-3">
                        <p class="text-sm font-medium text-orange-900">Total Members</p>
                        <p class="text-lg font-semibold text-orange-900">{{ $records->count() }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Member Records -->
    <div class="bg-white rounded-lg shadow">
        <div class="px-6 py-4 border-b border-gray-200">
            <h3 class="text-lg font-semibold text-gray-900">Member Share Bonus Records</h3>
        </div>
        
        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                    <tr>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Member</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Account Number</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Savings Balance</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Share Percentage</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Share Bonus Amount</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    @forelse($records as $record)
                        <tr class="hover:bg-gray-50">
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div class="flex items-center">
                                    <div class="flex-shrink-0 h-10 w-10">
                                        <div class="h-10 w-10 rounded-full bg-gray-300 flex items-center justify-center">
                                            <span class="text-sm font-medium text-gray-700">
                                                {{ substr($record->member->first_name, 0, 1) }}{{ substr($record->member->last_name, 0, 1) }}
                                            </span>
                                        </div>
                                    </div>
                                    <div class="ml-4">
                                        <div class="text-sm font-medium text-gray-900">
                                            {{ $record->member->first_name }} {{ $record->member->last_name }}
                                        </div>
                                        <div class="text-sm text-gray-500">
                                            {{ $record->member->email }}
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                {{ $record->member->account_number }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                {{ number_format($record->savings_balance, 2) }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                {{ number_format($record->share_percentage, 4) }}%
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                {{ number_format($record->share_bonus_amount, 2) }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                @if($record->applied_at)
                                    <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                                        Applied
                                    </span>
                                @else
                                    <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800">
                                        Pending
                                    </span>
                                @endif
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" class="px-6 py-4 text-center text-gray-500">
                                No records found for this statement.
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        
        @if($records->hasPages())
            <div class="px-6 py-4 border-t border-gray-200">
                {{ $records->links() }}
            </div>
        @endif
    </div>

    @if($statement->notes)
        <!-- Notes -->
        <div class="bg-white rounded-lg shadow p-6">
            <h3 class="text-lg font-semibold text-gray-900 mb-4">Notes</h3>
            <p class="text-gray-700">{{ $statement->notes }}</p>
        </div>
    @endif
</div>
@endsection